In [3]:
import numpy as np
# Let's define a one-dimensional array
list_1 = [50, 60, 80, 100, 200, 300, 500, 600]
list_1

[50, 60, 80, 100, 200, 300, 500, 600]

In [12]:
# Let's create a numpy array from the list "my_list"
my_numpy_array = np.array(list_1)
my_numpy_array

array([ 50,  60,  80, 100, 200, 300, 500, 600])

In [3]:
type(my_numpy_array)

numpy.ndarray

In [10]:
# Multi-dimensional (Matrix definition)
my_matrix = np.array([[2,3,5],[4,5,6],[5,6,7]])
my_matrix

array([[2, 3, 5],
       [4, 5, 6],
       [5, 6, 7]])

In [15]:
#MINI CHALLENGE #1: 
#Write a code that creates the following 2x4 numpy array

#...
#[[3 7 9 3] 
#[4 3 2 2]]
#```
x = np.array([ [3, 7, 9, 3], [4, 3, 2, 2] ])
x

array([[3, 7, 9, 3],
       [4, 3, 2, 2]])

In [3]:
# "rand()" uniform distribution between 0 and 1
import numpy as np
x = np.random.rand(20)
x

array([0.42168991, 0.36377077, 0.15889394, 0.23292675, 0.47527097,
       0.41017857, 0.3271447 , 0.21611793, 0.05508819, 0.31628162,
       0.04760483, 0.93565652, 0.40434534, 0.74255935, 0.99328682,
       0.27804829, 0.15072289, 0.59448511, 0.78335809, 0.59216684])

In [4]:
# you can create a matrix of random number as well
x = np.random.rand(3,3)
x

array([[0.48420892, 0.38331171, 0.60714946],
       [0.32399403, 0.08079314, 0.93601998],
       [0.52764094, 0.60536598, 0.45857334]])

In [6]:
# "randint" is used to generate random integers between upper and lower bounds
x = np.random.randint(1, 50)
x

12

In [7]:
# "randint" can be used to generate a certain number of random itegers as follows
x = np.random.randint(1, 100, 15)
x

array([19, 65, 60, 56, 74, 50, 59, 15, 21, 11, 25, 46, 33, 61, 70])

In [9]:
#creates an evenly spaced values within a given interval
x = np.arange(1, 20)
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [14]:
# create a diagonal of ones and zeros everywhere else
x = np.eye(7)
x

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

In [18]:
# Matrix of ones
x = np.ones((7, 7))
x

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

In [22]:
# Array of zeros
x = np.zeros((6,6))
x

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [23]:
# Array of zeros
x = np.zeros(6)
x

array([0., 0., 0., 0., 0., 0.])

In [26]:
#MINI CHALLENGE #2:

#Write a code that takes in a positive integer "x" from the user and creates a 1x10 array with random numbers ranging from 0 to "x"
x = int(input("Enter a No: "))
s = np.random.randint(1, x, 10)
s

array([ 8, 17, 30,  6, 26, 40,  9, 28, 41, 10])

In [2]:
# np.arange() returns an evenly spaced values within a given interval
import numpy as np
x = np.arange(1, 10)
x

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
y = np.arange(1, 10)
y

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
#add two numpy arrays together
sum = x + y
sum

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [8]:
squared = x ** 2
squared

array([ 1,  4,  9, 16, 25, 36, 49, 64, 81])

In [10]:
sqrt = np.sqrt(squared)
sqrt

array([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [11]:
#minichallenge 3
#Given the x and y values below, obtain the distance between them.
x = [5, 7, 20]
y = [9, 15, 4]

x = np.array([5, 7, 20])
y = np.array([9, 15, 4])

distance = np.sqrt( x**2 + y**2 )
distance

array([10.29563014, 16.55294536, 20.39607805])

In [12]:
#access specific element from the numpy array

my_numpy_array = ([3, 5, 6, 2, 8, 10, 20, 50])
my_numpy_array

[3, 5, 6, 2, 8, 10, 20, 50]

In [13]:
my_numpy_array[0]

3

In [14]:
#starting from the first index 0 up untill and not inluding the last element
my_numpy_array[0:3]

[3, 5, 6]

In [21]:
#broadcasting, alternating several values in a numpy array at once
my_numpy_array[0:4] = 7
my_numpy_array


TypeError: can only assign an iterable

In [22]:
#let's define a two dimensional numpy array
matrix = np.random.randint(1, 10, (4, 4))
matrix

array([[9, 2, 9, 3],
       [6, 2, 6, 2],
       [4, 9, 4, 6],
       [4, 1, 3, 2]])

In [23]:
#get a row from a matrix
matrix[0]

array([9, 2, 9, 3])

In [24]:
#get one element [row] [coloumn]
matrix[0][3]

3

In [25]:
#minichallenge 4
#in the following matrix replace the last row with 0.
'''2 30 20 -2 -4
   3 4  40 -3 -2
  -3 -4 -6 90 10
  25 45 32 78 89
  23 56 87 9 10'''
x = np.array([[2, 30, 20, -2, -4],
              [3, 4, 40, -3, -2],
              [-3, -4, -6, 90, 10],
              [25, 45, 32, 78, 89],
              [23, 56, 87, 9, 10]])
x

array([[ 2, 30, 20, -2, -4],
       [ 3,  4, 40, -3, -2],
       [-3, -4, -6, 90, 10],
       [25, 45, 32, 78, 89],
       [23, 56, 87,  9, 10]])

In [26]:
x[4] = 0
x

array([[ 2, 30, 20, -2, -4],
       [ 3,  4, 40, -3, -2],
       [-3, -4, -6, 90, 10],
       [25, 45, 32, 78, 89],
       [ 0,  0,  0,  0,  0]])

In [12]:
#perform element selection conditional
matrix = np.random.randint(1, 10, (5, 5))
matrix

array([[2, 1, 1, 8, 7],
       [7, 1, 3, 7, 8],
       [7, 4, 5, 3, 1],
       [9, 1, 2, 5, 5],
       [4, 6, 9, 3, 4]])

In [13]:
new_matrix = matrix[ matrix > 7 ]
new_matrix

array([8, 8, 9, 9])

In [14]:
#obtain odd elements only
new_matrix = matrix[ matrix % 2 == 1 ]
new_matrix

array([1, 1, 7, 7, 1, 3, 7, 7, 5, 3, 1, 9, 1, 5, 5, 9, 3])

In [15]:
#obtain even elements only
new_matrix = matrix[ matrix % 2 == 0 ]
new_matrix

array([2, 8, 8, 4, 2, 4, 6, 4])

In [16]:
#minichallenge 5
#replace negative elements by 0 and replace odd elements with -2
'''2 30 20 -2 -4
   3 4 40 -3 -2
   -3 4 -6  90 10
   25 45 34 22 12
   13 24 22 32 37'''
x = np.array([[2 ,30, 20, -2, -4],
              [3, 4, 40, -3, -2],
              [-3, 4, -6, 90, 10],
              [25, 45, 34, 22, 12],
              [13, 24, 22, 32, 37]])

In [17]:
x[x < 0] = 0
x[x % 2 == 1] = -2
x

array([[ 2, 30, 20,  0,  0],
       [-2,  4, 40,  0,  0],
       [ 0,  4,  0, 90, 10],
       [-2, -2, 34, 22, 12],
       [-2, 24, 22, 32, -2]])